// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXqADdwQpKCd7SAI4w2SbcRXilNYp0etY',
    appId: '1:410992872645:web:176440c8305fbe7289b4ac',
    messagingSenderId: '410992872645',
    projectId: 'dictionary-app-flutter-64e63',
    authDomain: 'dictionary-app-flutter-64e63.firebaseapp.com',
    storageBucket: 'dictionary-app-flutter-64e63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSleevAE72G_yO4B7fbp-y3j5orL-_5jw',
    appId: '1:410992872645:android:60f31e291f33c70a89b4ac',
    messagingSenderId: '410992872645',
    projectId: 'dictionary-app-flutter-64e63',
    storageBucket: 'dictionary-app-flutter-64e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbikzcyLChHu241ChsNmiJlyv7VRhQ3oA',
    appId: '1:410992872645:ios:7ce067154397af6589b4ac',
    messagingSenderId: '410992872645',
    projectId: 'dictionary-app-flutter-64e63',
    storageBucket: 'dictionary-app-flutter-64e63.appspot.com',
    iosClientId: '410992872645-60fsk3r49jpv9nkh0dnicef7uq24nok2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEnglishApp',
  );
}
